AWSTemplateFormatVersion: 2010-09-09
Description: Route53 Hosted zone & Record set creation

Parameters:
  HOSZONE:
    Description: "Name of Hosted zone"
    Type: String
  PUBIP:
    Description: "Nginx IP Address"
    Type: String

Resources:
  DNS: 
    Type: "AWS::Route53::HostedZone"
    Properties: 
      HostedZoneConfig: 
        Comment: 'My hosted zone'
      Name: !Sub ${HOSZONE}

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref DNS
      Name: !Sub "*.${HOSZONE}"
      Type: A
      TTL: '900'
      ResourceRecords:
      - !Sub ${PUBIP}
