apiVersion: v1
kind: ConfigMap
metadata:
  name: gangway
data:
  gangway.yaml: |
    # The cluster name. Used in UI and kubectl config instructions.
    # Env var: GANGWAY_CLUSTER_NAME
    clusterName: "hollowcluster"

    # OAuth2 URL to start authorization flow.
    # Env var: GANGWAY_AUTHORIZE_URL
    authorizeURL: "https://dex.groofy.live/dex/auth" #replace the domain name with your domain

    # OAuth2 URL to obtain access tokens.
    # Env var: GANGWAY_TOKEN_URL
    tokenURL: "https://dex.groofy.live/dex/token" #replace the domain name with your domain

    # Used to specify the scope of the requested Oauth authorization.
    scopes: ["openid", "profile", "email", "offline_access", "groups"]

    # Where to redirect back to. This should be a URL where gangway is reachable.
    # Typically this also needs to be registered as part of the oauth application
    # with the oAuth provider.
    # Env var: GANGWAY_REDIRECT_URL
    redirectURL: "https://gangway.groofy.live/callback" #replace the domain name with your domain

    # API client ID as indicated by the identity provider
    # Env var: GANGWAY_CLIENT_ID
    clientID: "gangway"

    # API client secret as indicated by the identity provider
    # Env var: GANGWAY_CLIENT_SECRET
    clientSecret: "mfgDcwBEgSgFehUFdQh2fhbftrgPOQWy0Q05gZgY8bs=" #secret key from prerequisites again. This should match the Dex key

    # The JWT claim to use as the username. This is used in UI.
    # Default is "nickname".
    # Env var: GANGWAY_USERNAME_CLAIM
    usernameClaim: "sub"

    # The JWT claim to use as the email claim. This is used to name the
    # "user" part of the config. Default is "email".
    # Env var: GANGWAY_EMAIL_CLAIM
    emailClaim: "email"

    # The API server endpoint used to configure kubectl
    # Env var: GANGWAY_APISERVER_URL
    apiServerURL: https://kubeapiserver.groofy.live:6443 #This should be your k8s API URL
      
    trustedCAPath: "/etc/gangway/cacert.crt"
